config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
  	resources :comments
  end
  
  root "posts#index"

  get '/about', to: 'pages#about'
  get '/profile', to: 'pages#profile'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new	
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])		
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Atrás</p>
	</div>

	<% if user_signed_in? %>
		<p><%= link_to 'Deletar', [comment.post, comment],
			method: :delete,
			class: "button",
			data: { confirm: 'Tem certeza ?'} %>
		</p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feicebuque</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do%>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Sobre", about_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Perfil", profile_path %></li>
			<% end %>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"> Admin Login</p>
		<% end %>
	</div>
	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p> Todos os posts </p>
				<%elsif current_page?(about_path)%>
				<p>Sobre</p>
				<% else %>
				<%= link_to "Todos os posts", root_path %>
				<% end %>

			<div class="buttons">
				<% if user_signed_in? %>
				<button class="button"><%= link_to "Novo Post", new_post_path %></button>
				<button class="button"><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></button>
			
				<% else %>
				<button class="button"><%= link_to "Log In", new_user_session_path %></button>				
			
				<% end %>
			</div>		
		</div>
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

	<%= yield %>

	</div>


</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<p>Essa página está no ar por incríveis 3 dias. Fundada no dia 8/12/2015 revolucionou a internet catastroficamente. Várias pessoas já dizem que esse site irá substituir o Google. Como por exemplo: </p> <br>
	<p>"Esse site tá muito bonito!" - Minha mãe.</p>
	<p>"Eu não lembro a minha senha." - Meu irmão</p>
	<p>"Ô louco, bicho!" - Faustão</p><br>

	<p>Entre muitos outros!</p>
	<br>
	<div id="profile_image">
		<%= image_tag "thumbs.jpg" %>
	</div>
	<p> Felipe Osório de Oliveira</p>
	<p> Guilherme dos Santos Ribeiro Sant'Ana </p>
</div>

app/views/pages/profile.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>
	<div id="content">
		<h1 margin-left="10px">Bem vindo!</h1> 	
		<p><%= current_user.email%></p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2> <%= pluralize(@post.errors.count, "erro") %> foram encontrados ao tentar salvar esse post</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %> </li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :title %> <br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %> <br>
			<%= f.text_area :body%>
		</p>

		<p>
			<%= f.submit %>
		</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1> Editar Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post|%>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post%></h2>
		<p class="date"><%= post.created_at.strftime("%B, %d, %Y")%></p>
	</div>
<%end%>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1> Novo Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class ="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago

		<% if user_signed_in? %>
		| <%= link_to 'Editar', edit_post_path(@post) %> |
		<%= link_to 'Deletar', post_path(@post), method: :delete, data: { confirm: 'Tem certeza?' } %>
		<% end %>
	</p>

	<p class="body"><%= @post.body %></p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comentários</h2>
		<%= render @post.comments %>

		<h3>Adicionar um comentário:</h3>
		<%= render "comments/form" %>
	</div>
</div>